#!/bin/sh

# This will cap your wired server and wired client uploads at 5k/sec.
# MAXSPEED is in bytes.

# Setup a few variables
MAXSPEED=5120
RULENUM=00075
IP=any
INTERFACE=en0

# Launch throttled with cap of 5k/sec.
/usr/local/sbin/throttled -s $MAXSPEED -d 5555 -r $RULENUM || exit

# skip your internal network, these rules are for 192.168.x.x and 10.x.x.x
/sbin/ipfw add $RULENUM skipto `expr $RULENUM + 1` ip from $IP to 192.168.0.0/16 out xmit $INTERFACE
/sbin/ipfw add $RULENUM skipto `expr $RULENUM + 1` ip from $IP to 10.0.0.0/8 out xmit $INTERFACE

# bind for wired server
/sbin/ipfw add $RULENUM divert 5555 tcp from $IP 2001 to any out xmit $INTERFACE

# bind for wired client uploads
/sbin/ipfw add $RULENUM divert 5555 tcp from $IP to any 2001 out xmit $INTERFACE