#!/bin/sh

# This will cap your outgoing speed to 5k/sec.
# You probably want to set this higher.
# MAXSPEED is in bytes.

# Setup a few variables
MAXSPEED=5120
RULENUM=00075
IP=any
INTERFACE=en0

# Launch throttled with cap of 5k/sec.
/usr/local/sbin/throttled -s $MAXSPEED -d 5555 -r $RULENUM || exit

# Redirect all ougoing traffic to throttled
/sbin/ipfw add $RULENUM divert 5555 ip from $IP to any out xmit $INTERFACE